# Generated by Django 4.2.16 on 2024-11-05 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bancopreguntas',
            fields=[
                ('idpregunta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='bancorespuestas',
            fields=[
                ('idrespuesta', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('idpregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.bancopreguntas')),
            ],
        ),
        migrations.CreateModel(
            name='planestudios',
            fields=[
                ('idplan', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='cursos',
            fields=[
                ('idcurso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('idplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.planestudios')),
            ],
        ),
        migrations.CreateModel(
            name='bancoresultados',
            fields=[
                ('idresultado', models.AutoField(primary_key=True, serialize=False)),
                ('resultado', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('idpregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.bancopreguntas')),
                ('idrespuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.bancorespuestas')),
            ],
        ),
        migrations.AddField(
            model_name='bancopreguntas',
            name='idcurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.cursos'),
        ),
        migrations.AddField(
            model_name='bancopreguntas',
            name='idplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.planestudios'),
        ),
    ]
